server:
  port: 7001

spring:
  # 3.sharding-jdbc读写分离
  shardingsphere:
    # 数据源配置
    datasource:
      names: master,slave
      # master数据源
      master:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://49.234.56.182:3306/mall?useUnicode=yes&characterEncoding=UTF-8
        username: root
        password: 123456
      # slave数据源
      slave:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://49.234.56.182:3307/mall?useUnicode=yes&characterEncoding=UTF-8
        username: root
        password: 123456
    # 读写分离配置
    masterslave:
      # 从库负载均衡类型：随机
      load-balance-algorithm-type: round_robin
      name: ms
      master-data-source-name: master
      slave-data-source-names: slave

  # 1.Hikari datasource
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://49.234.56.182:3306/mall?useUnicode=yes&characterEncoding=UTF-8&useSSL=false
#    username: root
#    password: 123456
#    hikari:
#      minimum-idle: 5
#      maximum-pool-size: 20
#      idle-timeout: 60000

  # 2.Druid datasource
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://49.234.56.182:3306/mall?useUnicode=yes&characterEncoding=UTF-8&useSSL=false
#    username: root
#    password: 123456
#    type: com.alibaba.druid.pool.DruidDataSource
#    druid:
#      initial-size: 5
#      min-idle: 5
#      max-active: 20
#      max-wait: 60000


# mybatis
mybatis:
  type-aliases-package: com.summary.mysql.domain
  mapper-locations: classpath*:/mapper/*.xml
